#!/bin/sh
# Ruby gem:create a new gem directory structure and copy in some starter files                                             
pwd=`pwd`
basename=`basename $pwd`
source='/usr/local/bin/gem-new-source-files'
camelize=`camelize $basename`

mkdir -p lib
mkdir -p test/unit
cp -i $source/gemspec $basename.gemspec
cp -i $source/lib/foo.rb lib/$basename.rb
cp -i $source/test/unit/foo_test.rb test/unit/${basename}_test.rb
sed -i "s/{name}/$basename/;s/{camelize}/$camelize/" $basename.gemspec  lib/$basename.rb test/unit/${basename}_test.rb

git init
git add *
git commit -m 'first' -a




