#!/usr/bin/ruby -w
input_ruby_filename,output_rdoc_filename=ARGV
File.exist?(input_ruby_filename) or raise "File #{input_ruby_filename} does not exist"
input=File.new(input_ruby_filename)
output=''

while line=input.gets
  if line=~/^##/ or line=~/^\s+/ or line=~/^$/ then break end
  if line=~/^#!/ or line=~/^# -\*- coding: / then next end
  line=~/^# {0,1}/
  output+=$'
end

File.open(output_rdoc_filename, 'w') {|f| f.write(output) }
